# Default values for splunk-connect-for-syslog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

splunk:
  {}
#   hec_url: ""
#   hec_token: ""
#   hec_verify_tls: "yes"

sc4s: 
  {}
#   existingCert: example-com-tls
#   vendor_product:
#     - name: checkpoint
#       ports:
#         tcp: [9000]
#         udp: [9000]
#       options:
#         listen:
#           old_host_rules: "yes"

#     - name: infoblox
#       ports:
#         tcp: [9001, 9002]
#         tls: [9003]
#     - name: fortinet
#       ports:
#         ietf_udp:
#           - 9100
#           - 9101
#   context_files:
#     splunk_metadata.csv: |-
#       cisco_meraki,index,foo
#     host.csv: |-
#       192.168.1.1,HOST,foo
#       192.168.1.2,HOST,moon
#    config_files:
#      app_parser_test_big.conf: |-
#       #/opt/sc4s/local/config/filters/app-postfilter-drop_metadata.conf
#        block parser app-postfilter-cisco_asa_metadata() {
#        channel {
#          rewrite {
#            unset(value('fields.sc4s_recv_time'));
#            };
#          };
#        };
#        application app-postfilter-cisco_asa_metadata[sc4s-postfilter] {
#          filter {
#            'cisco' eq "${fields.sc4s_vendor}"
#            and 'asa' eq "${fields.sc4s_product}"
#          };
#          parser { app-postfilter-cisco_asa_metadata(); };
#        };

#   addons:
#     config.yaml: |-
#       ---
#       addons:
#         - Example addon
#         - barracuda
#         - cisco
#         - paloalto
#         - vmware
#         - dell
#         - zscaler
#         - checkpoint
#         - kaspersky
#         - mcafee
#         - ibm
#         - tanium
#         - arista
#         - ubiquiti
#         - forcepoint
#         - netapp
#         - clearswift
#         - cylance
#         - cyberark
#         - avi
#         - darktrace
#         - beyondtrust
#         - qumulo
#         - liveaction
#         - juniper
#         - hp
#         - broadcom
#         - aruba
#         - f5
#         - imperva
#         - fireeye
#         - trendmicro
#         - novell
#         - brocade
#         - ossec
#         - vectra
#         - microsoft
#         - mikrotik
#         - nutanix
#         - proofpoint
#         - tenable
#         - pulse
#         - stealthwatch
#         - netscout
#         - purestorage
#         - spectracom
#         - xypro
#         - raritan
#         - ricoh
#         - avaya
#         - secureauth
#         - infoblox
#         - schneider
#         - isc
#         - fortinet
#         - solace
#         - radware
#         - riverbed
#         - pfsense
#         - github
#         - buffalo
#         - varonis
#         - alsid
#         - sophos
#         - netmotion
#         - tintri
#         - alcatel
#         - cohesity
#         - ruckus
#         - polycom
#         - citrix
#         - haproxy
#         - a10networks
#         - microfocus
#         - syslogng
#         - wallix
#         - thycotic
#         - tim

image:
  repository: ghcr.io/splunk/splunk-connect-for-syslog/container3
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

persistence:
  enabled: true
  annotations: {}
  size: "10Gi"

#  storageClass: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  usemetallb: {}
  metallbsharingkey: {}

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

nodeAffinity: {}

tolerations: []

externalTrafficPolicy: Cluster
