version: "3"
services:
  test:
    build: ./tests
    links:
      - splunk
      - sc4s
    volumes:
      - sc4s-tests:/work/tests
      - sc4s-results:/work/test-results
    environment:
      - SPLUNK_PASSWORD

  sc4s:
#    image: rfaircloth/scs:latest
    build:
      context: ./package
      args:
        RH_ORG: $RH_ORG
        RH_ACTIVATION: $RH_ACTIVATION
    hostname: sc4s
    ports:
      - "514"
      - "601"
      - "514/udp"
      - "5514"
      - "5514/udp"
    stdin_open: true
    tty: true
    links:
      - splunk
    environment:
      - SPLUNK_HEC_URL
      - SPLUNK_HEC_STATSURL
      - SPLUNK_HEC_TOKEN
      - SPLUNK_CONNECT_METHOD
      - SPLUNK_DEFAULT_INDEX
      - SPLUNK_METRICS_INDEX
#    logging:
#      driver: splunk
#      options:
#        splunk-token: a778f63a-5dff-4e3c-a72c-a03183659e94
#        splunk-url: https://splunk:8088/services/collector/event
#        splunk-index: main
#        splunk-insecureskipverify: true
#        splunk-verify-connection: false
  splunk:
    image: splunk/splunk:latest
    hostname: splunk
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    environment:
      - SPLUNK_HEC_TOKEN
      - SPLUNK_PASSWORD
      - SPLUNK_START_ARGS
#    logging:
#      driver: splunk
#      options:
#        splunk-token: a778f63a-5dff-4e3c-a72c-a03183659e94
#        splunk-url: https://splunk:8088/services/collector/event
#        splunk-index: main
#        splunk-insecureskipverify: true
#        splunk-verify-connection: false
volumes:
  sc4s-tests:
    external: true
  sc4s-results:
    external: true
