#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
version: "3.2"
services:
  test:
    build: ./tests
    links:
      - splunk
      - sc4s
    volumes:
      - sc4s-tests:/work/tests
      - sc4s-results:/work/test-results
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}

  sc4s:
    image: rfaircloth/scs:${CIRCLE_SHA1}
    hostname: sc4s
    ports:
      - "514"
      - "601"
      - "514/udp"
      - "5514"
      - "5514/udp"
    stdin_open: true
    tty: true
    links:
      - splunk
    environment:
      - SPLUNK_HEC_URL=${SPLUNK_HEC_URL}
      - SPLUNK_HEC_STATSURL=${SPLUNK_HEC_STATSURL}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_CONNECT_METHOD=${SPLUNK_CONNECT_METHOD}
      - SPLUNK_DEFAULT_INDEX=${SPLUNK_DEFAULT_INDEX}
      - SPLUNK_METRICS_INDEX=${SPLUNK_DEFAULT_INDEX}
sc4s-juniper:
    image: splunk/scs:latest
    build:
      context: ./package
#      cache_from:
#        - registry.access.redhat.com/ubi7/ubi
#        - registry.access.redhat.com/rhel7/rhel
#        - rfaircloth/scs:edge
      args:
        RH_ORG: ${RH_ORG}
        RH_ACTIVATION: ${RH_ACTIVATION}
    hostname: sc4s-juniper
    ports:
      - "514"
    stdin_open: true
    tty: true
    links:
      - splunk
    environment:
      - SPLUNK_HEC_URL=${SPLUNK_HEC_URL}
      - SPLUNK_HEC_STATSURL=${SPLUNK_HEC_STATSURL}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_CONNECT_METHOD=${SPLUNK_CONNECT_METHOD}
      - SPLUNK_DEFAULT_INDEX=${SPLUNK_DEFAULT_INDEX}
      - SPLUNK_METRICS_INDEX=${SPLUNK_DEFAULT_INDEX}
      - SYSLOG_PRESUME_FILTER=juniper_netscreen
#    logging:
#      driver: splunk
#      options:
#        splunk-token: a778f63a-5dff-4e3c-a72c-a03183659e94
#        splunk-url: https://splunk:8088/services/collector/event
#        splunk-index: main
#        splunk-insecureskipverify: true
#        splunk-verify-connection: false
  splunk:
    image: splunk/splunk:latest
    hostname: splunk
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    environment:
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_START_ARGS=${SPLUNK_START_ARGS}
      - SPLUNK_APPS_URL=${SPLUNK_APPS_URL}
      - SPLUNKBASE_USERNAME=${SPLUNKBASE_USERNAME}
      - SPLUNKBASE_PASSWORD=${SPLUNKBASE_PASSWORD}
    volumes:
      - ./splunk/SA-syslog-ng:/opt/splunk/etc/apps/SA-syslog-ng
#    logging:
#      driver: splunk
#      options:
#        splunk-token: a778f63a-5dff-4e3c-a72c-a03183659e94
#        splunk-url: https://splunk:8088/services/collector/event
#        splunk-index: main
#        splunk-insecureskipverify: true
#        splunk-verify-connection: false
volumes:
  sc4s-tests:
    external: true
  sc4s-results:
    external: true
