#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
version: "3.2"
services:
  test:
    build: ./tests
    links:
      - splunk
      - sc4s
    volumes:
      - sc4s-results:/work/test-results
    environment:
      - SPLUNK_USER=admin
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_HOST=splunk
      - SYSLOG_HOST=sc4s

  sc4s:
    image: splunk/scs:latest
    build:
      context: ./package
      args:
        RH_ORG: ${RH_ORG}
        RH_ACTIVATION: ${RH_ACTIVATION}
    hostname: sc4s
    command: -det
    ports:
      - "514:514"
      - "601:601"
      - "514:514/udp"
      - "5000"
      - "5000:5000/udp"
      - "6514:6514"
    stdin_open: true
    tty: true
    links:
      - splunk
    environment:
      - SPLUNK_HEC_URL=${SPLUNK_HEC_URL}
      - SPLUNK_HEC_STATSURL=${SPLUNK_HEC_STATSURL}
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_CONNECT_METHOD=${SPLUNK_CONNECT_METHOD}
      - SPLUNK_DEFAULT_INDEX=${SPLUNK_DEFAULT_INDEX}
      - SPLUNK_METRICS_INDEX=${SPLUNK_DEFAULT_INDEX}
      - SC4S_SOURCE_TLS_ENABLE=no
      - SC4S_DEST_SPLUNK_HEC_TLS_VERIFY=no
      - SC4S_LISTEN_JUNIPER_NETSCREEN_TCP_PORT=5000
      - SC4S_LISTEN_CHECKPOINT_SPLUNK_TCP_PORT=6000
#      - SC4S_ARCHIVE_CHECKPOINT=yes
      - SC4S_ARCHIVE_GLOBAL=yes
    volumes:
      - ./tls:/opt/syslog-ng/tls
  splunk:
    image: splunk/splunk:latest
    hostname: splunk
    ports:
      - "8000:8000"
      - "8088:8088"
      - "8089:8089"
    environment:
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_START_ARGS=${SPLUNK_START_ARGS}
      - SPLUNK_APPS_URL=${SPLUNK_APPS_URL}
      - SPLUNKBASE_USERNAME=${SPLUNKBASE_USERNAME}
      - SPLUNKBASE_PASSWORD=${SPLUNKBASE_PASSWORD}
    volumes:
      - splunk-etc:/opt/splunk/etc
volumes:
  sc4s-results:
    external: true
  splunk-etc:
    external: true
