site_name: Splunk Connect for Syslog
plugins: 
  - search
  - include_dir_to_nav
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-ZQQ3Q8N2WQ

markdown_extensions:
  - toc:
      permalink: True
  - smarty
  - fenced_code
  - sane_lists
  - codehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.blocks.tab:
      alternate_style: true


theme:
  name: "material"
  palette:
    primary: "black"
    accent: "orange"
  favicon: "logo.png"
  logo: "logo.png"

nav:
  - Home: "index.md"
  - Architecture and Load Balancers:
      - Read First: "architecture/index.md"
      - Scaling Solutions:
          - Performance Tests: "architecture/performance-tests.md"
          - Fine-Tuning:
              - TCP Optimization: "architecture/tcp-optimization.md"
              - UDP Optimization: "architecture/udp-optimization.md"
      - Load Balancers:
          - Overview: "architecture/lb/index.md"
          - Nginx: "architecture/lb/nginx.md"
          - F5: "architecture/lb/f5.md"
  - Getting Started:
      - Read First: "gettingstarted/index.md"
      - Quickstart Guide: "gettingstarted/quickstart_guide.md"
      - Splunk Setup: "gettingstarted/getting-started-splunk-setup.md"
      - Runtime Configuration: "gettingstarted/getting-started-runtime-configuration.md"
      - Select Runtime:
        - Podman + systemd: "gettingstarted/podman-systemd-general.md"
        - Docker CE + systemd: "gettingstarted/docker-systemd-general.md"
        - MicroK8s + Linux: "gettingstarted/k8s-microk8s.md"
        - Docker Compose: "gettingstarted/docker-compose.md"
        - Docker Desktop + Compose (MacOS): "gettingstarted/docker-compose-MacOS.md"
        - Bring your own Envionment: "gettingstarted/byoe-rhel8.md"
        - Docker&Podman offline installation: "gettingstarted/docker-podman-offline.md"
        - Ansible:
          - Docker Swarm: "gettingstarted/ansible-docker-swarm.md"
          - Podman/Docker: "gettingstarted/ansible-docker-podman.md"
          - mk8s: "gettingstarted/ansible-mk8s.md"
          - RKE2: "gettingstarted/ansible-rke2.md"
  - Create a parser: "create-parser.md"
  - Configuration: "configuration.md"
  - Destinations: "destinations.md"
  - Sources:
      - Read First: "sources/index.md"
      - Basic Onboarding: "sources/base"
      - Known Vendors: "sources/vendor"
  - SC4S Lite:
      - Intro: "lite.md"
      - Pluggable modules: "pluggable_modules.md"
  - Edge Processor: "edge_processor.md"
  - Troubleshooting:
      - SC4S Startup and Validation: "troubleshooting/troubleshoot_SC4S_server.md"
      - SC4S Logging and Troubleshooting Resources: "troubleshooting/troubleshoot_resources.md"
  - Dashboard: "dashboard.md"
  - Experiments: "experiments.md"
  - Upgrading SC4S: "upgrade.md"
  - SC4S FAQ: "faq.md"
