site_name: Splunk Connect for Syslog

extra:
  version:
    provider: mike

markdown_extensions:
  - toc:
      permalink: True
  - smarty
  - fenced_code
  - sane_lists
  - codehilite

theme:
  name: "material"
  palette:
    primary: "black"
    accent: "orange"
  favicon: "logo.png"
  logo: "logo.png"

nav:
  - Home: "index.md"
  - Getting Started:
      - "Read First": "gettingstarted/index.md"
      - "Podman + systemd": "gettingstarted/podman-systemd-general.md"
      - "Docker CE + systemd": "gettingstarted/docker-systemd-general.md"
      - "MicroK8s + Linux": "gettingstarted/k8s-microk8s.md"
      - "Docker Compose": "gettingstarted/docker-swarm-general.md"
      - "Docker Desktop + Compose (MacOS)": "gettingstarted/docker-compose-MacOS.md"
      - "Bring your own Envionment": "gettingstarted/byoe-rhel8.md"
      - "Quickstart Guide": "gettingstarted/quickstart_guide.md"
  - Architectural Considerations: "architecture.md"
  - Configuration: "configuration.md"
  - Development: "developing/index.md"
  - Destinations: "destinations.md"
  - Sources:
      - About: sources/index.md
      - Alcatel: sources/Alcatel/index.md
      - Alsid: sources/Alsid/index.md
      - Arista: sources/Arista/index.md
      - Avaya: sources/Avaya/index.md
      - "Avi Networks": sources/Avi_Networks/index.md
      - Brocade: sources/Brocade/index.md
      - Buffalo: sources/Buffalo/index.md
      - Checkpoint: sources/Checkpoint/index.md
      - Cisco: sources/Cisco/index.md
      - Citrix: sources/Citrix/index.md
      - Cohesity: sources/Cohesity/index.md
      - "Common Event Format": sources/CommonEventFormat/index.md
      - CyberArk: sources/CyberArk/index.md
      - Cylance: sources/Cylance/index.md
      - Dell: sources/Dell/index.md
      - "Dell RSA": sources/Dell_RSA/index.md
      - "Dell EMC": sources/Dell_EMC/index.md
      - F5: sources/F5/index.md
      - FireEye: sources/FireEye/index.md
      - Forcepoint: sources/Forcepoint/index.md
      - Fortinet: sources/Fortinet/index.md
      - HAProxy: sources/HAProxy/index.md
      - HPe: sources/HPe/index.md
      - IBM: sources/IBM/index.md
      - Imperva: sources/Imperva/index.md
      - InfoBlox: sources/InfoBlox/index.md
      - ISC: sources/ISC/index.md
      - "Log Extended Format": sources/LogExtendedEventFormat/index.md
      - Juniper: sources/Juniper/index.md
      - Loggen: sources/Loggen/index.md
      - McAfee: sources/McAfee/index.md
      - Microfocus: sources/Microfocus/index.md
      - Microsoft: sources/Microsoft/index.md
      - Mikrotik: sources/Mikrotik/index.md
      - NetApp: sources/NetApp/index.md
      - Netmotion: sources/Netmotion/index.md
      - Novell: sources/Novell/index.md
      - Nix: sources/nix/index.md
      - OSSEC: sources/Ossec/index.md
      - "Palo Alto Networks": sources/PaloaltoNetworks/index.md
      - "pfSense": sources/Pfsense/index.md
      - Polycom: sources/Polycom/index.md
      - Pulse: sources/Pulse/index.md
      - PureStorage: sources/PureStorage/index.md
      - Proofpoint: sources/Proofpoint/index.md
      - Qumulo: sources/Qumulo/index.md
      - Radware: sources/Radware/index.md
      - Raritan: sources/Raritan/index.md
      - Ricoh: sources/Ricoh/index.md
      - Schneider: sources/Schneider/index.md
      - "Simple Sources": sources/Simple/index.md
      - "Solace": sources/Solace/index.md
      - "Sophos": sources/Sophos/index.md
      - Spectracom: "sources/Spectracom/index.md"
      - Splunk: sources/Splunk/index.md
      - Broadcom: sources/Broadcom/index.md
      - Tanium: sources/Tanium/index.md
      - Tenable: sources/Tenable/index.md
      - Thycotic: sources/Thycotic/index.md
      - Tintri: sources/Tintri/index.md
      - Trend: sources/Trend/index.md
      - Ubiquiti: sources/Ubiquiti/index.md
      - Vectra: sources/Vectra/index.md
      - Varonis: sources/Varonis/index.md
      - VMware: sources/VMWare/index.md
      - Wallix: sources/Wallix/index.md
      - Zscaler: sources/Zscaler/index.md
  - Performance: "performance.md"
  - Troubleshooting:
      - SC4S Startup and Validation: "troubleshooting/troubleshoot_SC4S_server.md"
      - SC4S Logging and Troubleshooting Resources: "troubleshooting/troubleshoot_resources.md"
  - "Upgrading SC4S": "upgrade.md"
  - "SC4S FAQ": "faq.md"
