---
addons:
  - Example addon
  - barracuda
  - cisco
  - paloalto
  - vmware
  - dell
  - zscaler
  - checkpoint
  - kaspersky
  - mcafee
  - ibm
  - tanium
  - arista
  - ubiquiti
  - forcepoint
  - netapp
  - clearswift
  - cylance
  - cyberark
  - avi
  - darktrace
  - beyondtrust
  - qumulo
  - liveaction
  - juniper
  - hp
  - broadcom
  - aruba
  - f5
  - imperva
  - fireeye
  - trendmicro
  - novell
  - brocade
  - ossec
  - vectra
  - microsoft
  - mikrotik
  - nutanix
  - proofpoint
  - tenable
  - pulse
  - stealthwatch
  - netscout
  - purestorage
  - spectracom
  - xypro
  - raritan
  - ricoh
  - avaya
  - secureauth
  - infoblox
  - schneider
  - isc
  - fortinet
  - solace
  - radware
  - riverbed
  - pfsense
  - github
  - buffalo
  - varonis
  - alsid
  - sophos
  - netmotion
  - tintri
  - alcatel
  - cohesity
  - ruckus
  - polycom
  - citrix
  - haproxy
  - a10networks
  - microfocus
  - syslogng
  - wallix
  - thycotic
  - tim
  - semperis
  - powertech
  - thales
  - epic
  - trellix
  - netwrix
  - aviatrix
  - veeam
  - suricata
  - opswat
  - guardicore
