apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc4s-deployment
  namespace: sc4s
  labels:
    app: sc4s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc4s-app
  template:
    metadata:
      labels:
        app: sc4s-app
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: sc4s-config
      # Uncomment only if local parser used
      # - name: local-filter-config
      #   configMap:
      #     name: sc4s-local-filter-config 

      containers:
      - name: sc4s
        image: ghcr.io/splunk/splunk-connect-for-syslog/container3:latest
        imagePullPolicy: IfNotPresent

        resources:  
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"

        envFrom:
          - configMapRef:
              name: sc4s-config

        # Uncomment only if local parser used
        # volumeMounts:
        # - name: local-filter-config
        #   mountPath: /etc/syslog-ng/conf.d/local/config/app_parsers
        #   readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: sc4s-nodeport-service
  namespace: sc4s
spec:
  selector:
    app: sc4s-app
  type: NodePort 
  ports:
    - port: 514
      targetPort: 514
      name: "tcp514"
      protocol: TCP
      nodePort: 30514
    - port: 514
      targetPort: 514
      name: "udp514"
      protocol: UDP
      nodePort: 30514
    - port: 601
      targetPort: 601
      name: "tcp601"
      protocol: TCP
      nodePort: 30601
    - port: 6514
      targetPort: 6514
      name: "tcp6514"
      protocol: TCP
      nodePort: 30515
    - port: 8080
      targetPort: 8080
      name: "healthcheck"
      protocol: TCP
      nodePort: 30080
