name: Release Tagger

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+.e"

permissions:
  actions: read
  contents: write

jobs:
  update-semver-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Update Semver Tags
        uses: tchupp/actions-update-semver-tags@v1
